part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: Color(0x33000000),
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF0A0A0A),
  primary: Color(0xFF171717),
  primaryForeground: Color(0xFFFAFAFA),
  secondary: Color(0xFFF5F5F5),
  secondaryForeground: Color(0xFF171717),
  muted: Color(0xFFF5F5F5),
  mutedForeground: Color(0xFF737373),
  destructive: Color(0xFFE7000B),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFE7000B),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFFFFFFFF),
  border: Color(0xFFE5E5E5),
  extensions: const [AppColors()],
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: Color(0x7A000000),
  background: Color(0xFF0A0A0A),
  foreground: Color(0xFFFAFAFA),
  primary: Color(0xFFE5E5E5),
  primaryForeground: Color(0xFF171717),
  secondary: Color(0xFF262626),
  secondaryForeground: Color(0xFFFAFAFA),
  muted: Color(0xFF262626),
  mutedForeground: Color(0xFFA1A1A1),
  destructive: Color(0xFFFF6467),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFFF6467),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFF171717),
  border: Color(0x1AFFFFFF),
  extensions: const [
    AppColors(
      success: Color(0xFF4ADE80),
      warning: Color(0xFFFDE047),
      info: Color(0xFF60A5FA),
    ),
  ],
);

/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to Sublator.
///
/// Semantic colors for translation states and UI feedback beyond
/// what FColors provides (primary, destructive, muted).
class AppColors extends ThemeExtension<AppColors> {
  /// Success state: completed translation, verified credentials, "done" badges.
  final Color success;

  /// Warning state: partial translation, retry-available, degraded state.
  final Color warning;

  /// Info state: in-progress, connecting, pending action.
  final Color info;

  const AppColors({
    this.success = const Color(0xFF16A34A),
    this.warning = const Color(0xFFEAB308),
    this.info = const Color(0xFF2563EB),
  });

  @override
  AppColors copyWith({Color? success, Color? warning, Color? info}) {
    return AppColors(
      success: success ?? this.success,
      warning: warning ?? this.warning,
      info: info ?? this.info,
    );
  }

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other is! AppColors) return this;
    return AppColors(
      success: Color.lerp(success, other.success, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      info: Color.lerp(info, other.info, t)!,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppColors &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          warning == other.warning &&
          info == other.info;

  @override
  int get hashCode => Object.hash(runtimeType, success, warning, info);
}
