part of 'theme.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({
  required FColors colors,
  required FTypography typography,
  required bool touch,
}) {
  // ponytail: macOS Tahoe-inspired border radius — bumped for rounder feel.
  // sm: 6px (badges, small buttons), md: 8px (inputs, regular buttons),
  // lg: 12px (cards, panels), xl: 16px (dialogs, major containers).
  const borderRadius = FBorderRadius(
    xs2: .zero,
    xs: .zero,
    sm: BorderRadius.all(Radius.circular(6)),
    md: BorderRadius.all(Radius.circular(8)),
    lg: BorderRadius.all(Radius.circular(12)),
    xl: BorderRadius.all(Radius.circular(16)),
    xl2: BorderRadius.all(Radius.circular(16)),
    xl3: BorderRadius.all(Radius.circular(16)),
    pill: BorderRadius.all(Radius.circular(999)),
  );
  return FStyle(
    formFieldStyle: .inherit(
      colors: colors,
      typography: typography,
      touch: touch,
    ),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: colors.primary,
      borderRadius: borderRadius.md,
    ),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.body.lg.fontSize,
    ),
    tappableStyle: FTappableStyle(),
    borderRadius: borderRadius,
    borderWidth: 1,
    pagePadding: const .symmetric(vertical: 8, horizontal: 12),
    shadow: const [
      BoxShadow(color: Color(0x0d000000), offset: Offset(0, 1), blurRadius: 2),
    ],
    extensions: const [AppStyle()],
  );
}

/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final cardRadius = context.theme.style.app.cardRadius; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final cardRadius = context.theme.style.cardRadius; ✅
///
/// final cardRadius = context.theme.style.extension<AppStyle>().cardRadius; ❌
/// ```
extension FStyleExtensions on FStyle {
  AppStyle get app => extension<AppStyle>();
}

/// Custom style tokens unique to Sublator.
///
/// Desktop-specific layout constants and timing values that the
/// ForUI style system doesn't provide.
class AppStyle extends ThemeExtension<AppStyle> {
  /// Default sidebar width in logical pixels.
  final double sidebarWidth;

  /// Minimum sidebar width (user can drag narrower).
  final double sidebarMinWidth;

  /// Custom title bar height.
  final double titleBarHeight;

  /// Default transition duration for page changes and state feedback.
  final Duration transitionDuration;

  const AppStyle({
    this.sidebarWidth = 200,
    this.sidebarMinWidth = 150,
    this.titleBarHeight = 32,
    this.transitionDuration = const Duration(milliseconds: 200),
  });

  @override
  AppStyle copyWith({
    double? sidebarWidth,
    double? sidebarMinWidth,
    double? titleBarHeight,
    Duration? transitionDuration,
  }) {
    return AppStyle(
      sidebarWidth: sidebarWidth ?? this.sidebarWidth,
      sidebarMinWidth: sidebarMinWidth ?? this.sidebarMinWidth,
      titleBarHeight: titleBarHeight ?? this.titleBarHeight,
      transitionDuration: transitionDuration ?? this.transitionDuration,
    );
  }

  @override
  AppStyle lerp(covariant AppStyle? other, double t) {
    if (other is! AppStyle) return this;
    return AppStyle(
      sidebarWidth: sidebarWidth + (other.sidebarWidth - sidebarWidth) * t,
      sidebarMinWidth:
          sidebarMinWidth + (other.sidebarMinWidth - sidebarMinWidth) * t,
      titleBarHeight:
          titleBarHeight + (other.titleBarHeight - titleBarHeight) * t,
      transitionDuration:
          t < 0.5 ? transitionDuration : other.transitionDuration,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStyle &&
          runtimeType == other.runtimeType &&
          sidebarWidth == other.sidebarWidth &&
          sidebarMinWidth == other.sidebarMinWidth &&
          titleBarHeight == other.titleBarHeight &&
          transitionDuration == other.transitionDuration;

  @override
  int get hashCode => Object.hash(
        runtimeType,
        sidebarWidth,
        sidebarMinWidth,
        titleBarHeight,
        transitionDuration,
      );
}
