import '../../models/subtitle_document.dart';
import '../../models/subtitle_entry.dart';
import 'subtitle_writer.dart';

/// SubStation Alpha (.ass) writer.
///
/// Emits a minimal valid ASS file with one [Script Info] / [V4+ Styles] /
/// [Events] section. Override tags from [SubtitleEntry.assTags] are emitted
/// verbatim before the cue text, preserving round-trip fidelity for files
/// originally parsed by `dart_ass`. Speaker labels populate the Name column.
///
/// For file-based round-trip via `dart_ass`'s own `Ass.parse` + `Ass.toFile`,
/// prefer those methods directly — this writer is for in-memory serialisation
/// of a [SubtitleDocument].
class AssWriter implements SubtitleWriter {
  const AssWriter();

  @override
  String write(SubtitleDocument doc) {
    if (doc.entries.isEmpty) return '';
    final buf = StringBuffer()
      ..writeln('[Script Info]')
      ..writeln('; Generated by subtitle_translator')
      ..writeln('ScriptType: v4.00+')
      ..writeln('WrapStyle: 0')
      ..writeln('ScaledBorderAndShadow: yes')
      ..writeln('PlayResX: 384')
      ..writeln('PlayResY: 288')
      ..writeln()
      ..writeln('[V4+ Styles]')
      ..writeln(
          'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, '
          'OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, '
          'ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, '
          'Alignment, MarginL, MarginR, MarginV, Encoding')
      ..writeln(
          'Style: Default,Arial,16,&H00FFFFFF,&H000000FF,&H00000000,'
          '&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1')
      ..writeln()
      ..writeln('[Events]')
      ..writeln('Format: Layer, Start, End, Style, Name, MarginL, MarginR, '
          'MarginV, Effect, Text');

    for (final e in doc.entries) {
      buf.writeln('Dialogue: 0,${_assTime(e.startMs)},'
          '${_assTime(e.endMs)},Default,${e.speakerLabel ?? ''},'
          '0000,0000,0000,,${_textWithTags(e)}');
    }
    return buf.toString();
  }

  /// Joins override tags (verbatim) with the cue text. Tags are assumed to
  /// already be brace-wrapped (e.g. `{\b1}`) — that is what `dart_ass`
  /// emits via `AssOverrideTags.getAss()`.
  static String _textWithTags(SubtitleEntry e) {
    final tags = e.assTags;
    if (tags == null || tags.isEmpty) return effectiveText(e);
    return '${tags.join()}${effectiveText(e)}';
  }

  /// ASS time format: `H:MM:SS.cs` (1-digit hour, 2-digit hundredths).
  /// Mirrors `dart_ass`'s `convertMillisecondsToAssTime` so the output is
  /// byte-identical to what `dart_ass` would emit for the same instant.
  static String _assTime(int ms) {
    final h = ms ~/ 3600000 % 10;
    final m = (ms % 3600000) ~/ 60000;
    final s = (ms % 60000) ~/ 1000;
    final cs = (ms % 1000) ~/ 10;
    return '$h:${m.toString().padLeft(2, '0')}'
        ':${s.toString().padLeft(2, '0')}'
        '.${cs.toString().padLeft(2, '0')}';
  }
}
